framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        default_middleware: false
        middleware:
          - handle_message
      query.bus:
        default_middleware: false
        middleware:
          - handle_message
