security:
  password_hashers:
    hasher:
      id: App\Infrastructure\Auth\PasswordHasher

  providers:
    users:
      id: App\Infrastructure\Auth\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/user/login$
      stateless: true
      json_login:
        check_path: /api/user/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        username_path: email
        password_path: password

  access_control:
    - { path: ^/api/user/login, roles: PUBLIC_ACCESS }
