App\Application\Employee\Command\AddEmployeeToCompany\AddEmployeeToCompanyCommand:
  properties:
    companyId:
      - NotBlank: ~
      - Uuid: ~
    firstName:
      - NotBlank: ~
      - Length:
          min: 2
          max: 100
    lastName:
      - NotBlank: ~
      - Length:
          min: 2
          max: 100
    email:
      - NotBlank: ~
      - Email: ~
    phone:
      - Length:
          min: 5
          max: 20
      - Regex:
          pattern: '/^\+?[0-9\s\-]*$/'
          message: "Phone number can contain only numbers, spaces, dashes and optional leading plus sign."
