App\Application\Company\Command\CreateCompany\CreateCompanyCommand:
  properties:
    name:
      - NotBlank: ~
    nip:
      - NotBlank: ~
      - Regex:
          pattern: '/^\d{10}$/'
          message: "NIP must consist of exactly 10 digits."
    address:
      - NotBlank: ~
    city:
      - NotBlank: ~
    postalCode:
      - NotBlank: ~
      - Regex:
          pattern: '/^\d{2}-\d{3}$/'
          message: "The postal code must be in the format NN-NNN (e.g., 00-001)."

App\Application\Employee\Command\AddEmployeeToCompany\AddEmployeeToCompanyCommand:
  properties:
    companyId:
      - NotBlank: ~
    firstName:
      - NotBlank: ~
      - Length:
          min: 2
          max: 100
    lastName:
      - NotBlank: ~
      - Length:
          min: 2
          max: 100
    email:
      - NotBlank: ~
      - Email: ~
    phone:
      - Length:
          min: 5
          max: 20
      - Regex:
          pattern: '/^\+?[0-9\s\-]*$/'
          message: "Phone number can contain only numbers, spaces, dashes and optional leading plus sign."
