parameters:
  app.admin.email: "%env(ADMIN_EMAIL)%"
  app.admin.password: "%env(ADMIN_PASSWORD)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    App\Application\Shared\CommandBusHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: command.bus }

  App\:
    resource: "../src/"

  App\Infrastructure\Bus\CommandBus:
    arguments:
      - "@command.bus"

  Symfony\Component\PasswordHasher\PasswordHasherInterface: '@App\Infrastructure\Auth\PasswordHasher'
