parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Application\Shared\CommandBusHandlerInterface:
      public: true
      tags:
        - { name: messenger.message_handler, bus: command.bus }

  App\:
    resource: "../src/"

  App\Infrastructure\Bus\CommandBus:
    arguments:
      - "@command.bus"
